name: todo_list
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_route: 7.4.0
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  http: ^1.1.0
  json_annotation: ^4.8.1
  local_auth: ^2.1.7

dev_dependencies:
  auto_route_generator: 7.1.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
